spring:
  profiles:
    active:
      - dev

---
server: 
  port: 7006

spring:
  profiles: dev
  application:
    name: microservice-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://user:123456@localhost:8761/eureka/

---
server: 
  port: 7007

spring:
  profiles: test
  application:
    name: microservice-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://user:123456@localhost:8761/eureka/
